### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by littlecrow** [lednhatkhanh/graphSocial-Backend#1]
While I'm running the graphqlSocial-client-v2, server cannot load and display the dataloader error..

![image](https://user-images.githubusercontent.com/11881459/31047118-0a291b2a-a62f-11e7-9b7d-ece09f7f1877.png)

![image](https://user-images.githubusercontent.com/11881459/31047105-e626687c-a62e-11e7-9aa7-30712018d7bf.png)

**Comment by lednhatkhanh** [comment]
Removed optic, confirm that it fixed the confusion.
